name: Run po4a scripts
on:
  push:
#    paths:
#      - _translator-files/**.po
#      - wiki/en/*.md
    branches:
      - GH_actions_test3
jobs:
  run_po4a:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Retrieve po4a installation cache or create it if not found:
      - name: Cache po4a
        uses: actions/cache@v1.0.3
        id: cache-po4a
        with:
          path: "~/po4a"
          key: ${{ runner.os }}-po4a
      - name: Install or retrieve po4a from cache
        env:
          CACHE_HIT: ${{steps.cache-po4a.outputs.cache-hit}}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --force --recursive ~/po4a/* /
          else
            sudo apt install -yq gettext libsgmls-perl libyaml-tiny-perl opensp
            sudo dpkg -i _po4a-tools/po4a_0.64-alpha.deb
            mkdir -p ~/po4a
            for dep in po4a libcroco3 libosp5 sgml-base gettext libsgmls-perl libyaml-tiny-perl opensp; do
                dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/po4a/
            done
          fi

      # Paths changes filter:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            templates:
              - 'wiki/en/*.md'
            targets:
              - '_translator-files/po/*/*.po'
      - name: Update templates
        if: steps.filter.outputs.templates == 'true'
        run: ./_po4a-tools/po4a-update-templates.sh
      - name: Create targets
        if: steps.filter.outputs.targets == 'true'
        run: ./_po4a-tools/po4a-create-all-targets.sh

      # Commit and push results of scripts:
      - name: Commit files
        run: |
          git config --local user.name "ignotus666"
          git add .
          git commit -m "Push po4a changes" -a#

#      - name: Push changes # push the output folder to your repo
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ github.token }}
#          branch: GH_actions_test3

      - uses: actions/checkout@v2
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod a+w /srv/jekyll/Gemfile.lock && chmod 777 /srv/jekyll && jekyll build --future"
      - name: Zip Website
        run: zip -r ${{ github.workspace }}/website.zip _site/*
      - uses: actions/upload-artifact@v2
        name: Upload Website
        with:
          name: Website2
          path: ${{ github.workspace }}/website.zip
          retention-days: 15
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
