name: Stop merge

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Pull Request Labeler"]
    types:
      - completed
      - labeled

jobs:
  do-not-merge:
    if: github.event.label.name == 'Check Weblate'
    runs-on: ubuntu-22.04
    steps:
      - name: Check for label
        run: |
          echo "This Pull Request has the Check Weblate label"
          echo "If there are no pending translations to merge, remove the label"
          exit 1
